version: "3.8"
services:
  app:
    build: "https://github.com/dawidszafranski/test0dockerized-nodejs.git"
    restart: unless-stopped
    # ports:
    #   - "8081:80"
    volumes:
      - app_data:/usr/src/app
networks:
  default:
    name: scoobydoo
    external: true

volumes:
  app_data:
