version: "3.8"
services:
  app:
    build: "https://github.com/dawidszafranski/test0dockerized-nodejs.git"
    # build:
    #   context: "."
    #   dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   - "8081:80"
    volumes:
      - app_data:/usr/src/app
networks:
  default:
    external: true
    name: scoobydoo

volumes:
  app_data:
    external: true
